### ISSUE TITLE
GestureSign

### ISSUE THREAD

**Issue by Xin100** [AmazingApps/Amazing-Windows-Apps#100]
GestureSign
官网：https://zh.gesturesign.win/#/
一款开源的 Win10 全局手势控制软件。

**Comment by EMLVIRUS** [comment]
> Ditto-cp
官网：http://ditto-cp.sourceforge.net/
一款开源的强大的剪贴板增强工具。

Ear Trumpet
官网：https://github.com/File-New-Project/EarTrumpet
一款开源的可调节单个应用程序的音量的工具

均已存在，见于system分类

**Comment by Xin100** [comment]
之前浏览看漏了，已更正，谢谢提醒。

**Comment by EMLVIRUS** [comment]
> GestureSign
官网：https://zh.gesturesign.win/#/
一款开源的 Win10 全局手势控制软件。

该应用似乎针对触摸屏设计，但是对于鼠标的体验十分糟糕
目前而言，大多数人应该仍旧使用鼠标操作Windows，虽然该应用会有固定的目标市场，但是显然不适合作广泛推荐

该issue固定于pending，等待后续观察

**Comment by EMLVIRUS** [comment]
@Xin100 该应用重审中

**Comment by EMLVIRUS** [comment]
添加完成 感谢建议
