### ISSUE TITLE
开源协议与开源地址

### ISSUE THREAD

**Issue by EMLVIRUS** [AmazingApps/Amazing-Windows-Apps#108]
@liulex @taroxd @BBcaptain @lrinQVQ @shrderek 
开源协议与开源地址的表示方式已找到，目前该方式暂未发现影响观感的问题，若48小时内无异议将补充贡献指引与README的说明

- 例子[见于此](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/d13b180148441fe3c070040e6dde1c89929cd4d0)，如下图所示

![image](https://cloud.githubusercontent.com/assets/16912240/26335456/afd05428-3f9e-11e7-83a0-69d7a4cf68ed.png)
![image](https://cloud.githubusercontent.com/assets/16912240/26335546/5d4f7368-3f9f-11e7-9e44-d3dfb4e28f59.png)

**Comment by EMLVIRUS** [comment]
更新：图片悬浮提示修改表示格式为`协议@托管网站: 开源地址`
以上图中为例：`GPL@GitHub: https://github.com/audacity/audacity`

可简化README中描述的同时进一步优化观感（浏览器默认URL悬浮提示位于左下角，不易阅读）

**Comment by lrinQVQ** [comment]
Ok 我也帮忙

**Comment by lrinQVQ** [comment]
一天过去了orz

**Comment by EMLVIRUS** [comment]
明天剩下那几只还不冒泡就开工

**Comment by lrinQVQ** [comment]
好２３３３

**Comment by EMLVIRUS** [comment]
进展如下：

- [ ] audio.md
- [ ] chat-client.md
- [x] china-apps.md
- [ ] compression.md
- [ ] configuration.md
- [ ] customization.md
- [ ] data-recovery.md
- [ ] dev-tools.md
- [ ] downloader.md
- [ ] ebooks.md
- [ ] efficiency.md
- [ ] emails.md
- [ ] files.md
- [ ] games.md
- [ ] hardwares.md
- [ ] images.md
- [ ] internet.md
- [ ] online-storage.md
- [ ] practicals.md
- [ ] productivity.md
- [ ] security.md
- [ ] system.md
- [ ] terminal.md
- [ ] text-editor.md
- [ ] video.md

**Comment by EMLVIRUS** [comment]
无法找到开源协议及地址而暂时搁置：
* IntelliJ IDEA
* VMware Workstation Player
* VMware Workstation Pro

**Comment by lrinQVQ** [comment]
我有在commit里面贴地址啊233
