### ISSUE TITLE
硬盘女神

### ISSUE THREAD

**Issue by venmos** [AmazingApps/Amazing-Windows-Apps#123]
硬盘女神 Hardseed

不可言表的功能，中文开发者，有中文说明，有Windows/Linux可执行程序。

* https://github.com/yangyangwithgnu/hardseed

**Comment by EMLVIRUS** [comment]
@venmos

**Comment by venmos** [comment]
![](http://oqnim9qwv.bkt.clouddn.com/17-5-28/51197117.jpg)
