### ISSUE TITLE
add bomi

### ISSUE THREAD

**Issue by EMLVIRUS** [AmazingApps/Amazing-Windows-Apps#125]
see https://bomi-player.github.io/index.html

@venmos 你比较熟 可以麻烦你来写句description？

**Comment by venmos** [comment]
Bomi是一个开源软件，基于MPV播放器开发，为MPV播放器增强了图形化界面。适合对原生MPV配置文件与全快捷键操作头疼的用户。

**Comment by ivysrono** [comment]
@venmos 这个介绍几乎可以用在smplayer身上O(∩_∩)O

**Comment by EMLVIRUS** [comment]
@ivysrono 愿听君高见？

**Comment by ivysrono** [comment]
@EMLVIRUS 不用理我……等过几周我试的清楚了再来提smplayer
