### ISSUE TITLE
f.lux已上架至windows应用商店

### ISSUE THREAD

**Issue by shrderek** [AmazingApps/Amazing-Windows-Apps#148]
https://www.microsoft.com/zh-cn/store/p/flux/9n9kdphv91jt

**Comment by EMLVIRUS** [comment]
这一动作我早已注意到，这个上架的版本（99.9%的可能）是打包的 Win32 f.lux 4 beta，与 beta 发布时同步的动作

**Comment by shrderek** [comment]
虽然可能是移植版，但是通过windows应用商店更新比较方便，还是加上比较好
