### ISSUE TITLE
QuickLook

### ISSUE THREAD

**Issue by xupefei** [AmazingApps/Amazing-Windows-Apps#156]
国产。我自己觉得挺良心的233
https://github.com/xupefei/QuickLook

**Comment by EMLVIRUS** [comment]
@xupefei locale emulator的大神😃

**Comment by EMLVIRUS** [comment]
@xupefei 您自己的应用的话 个人觉得提交 PR 并由您亲自编写简介更加合适

**Comment by gloomy-ghost** [comment]
![default](https://user-images.githubusercontent.com/13086421/27124206-654c92ce-5144-11e7-9d79-870fa08b6c46.png)
被 SmartScreen 花式拦截，可以考虑下代码签名吗？certum家给开源项目特惠的证书价格还算可以接受

**Comment by xupefei** [comment]
我也想过那个签名，买来还可以顺便给LE签一个减少杀软误报。但是似乎那个是per-project的？想签两个项目就要买两份？
另外拿签名首次使用要买个读卡器，要价86美刀。做开源还要自己贴钱我岂不是十分sb😄

**Comment by ysc3839** [comment]
这个签名我也听说过，Git for Windows 和 ZeroNet 都在用。好像几十欧元一年？

**Comment by ysc3839** [comment]
应该不限制 per-project，我记得这个证书是写开发者名字的

**Comment by xupefei** [comment]
@gloomy-ghost 还是木有收到回信吗？

**Comment by gloomy-ghost** [comment]
嗯，15% off 但还是挺贵的……感觉这类东西直接在国内买会更便宜点
不过好歹明确了不只限定一个项目（
