### ISSUE TITLE
关于 蚂蚁笔记

### ISSUE THREAD

**Issue by Serious54088** [AmazingApps/Amazing-Windows-Apps#163]
笔记的免费版并没有同步功能。
但应用贴着免费标识，并描述是一款“开源云笔记”，是不是存在一点点误导性？容易让人误以为是免费的云笔记。
描述稍加说明会好一些吧。

**Comment by EMLVIRUS** [comment]
免费标记仅仅代表可以免费使用而已，不过确实可以改进一下描述
