### ISSUE TITLE
腾讯桌面管家

### ISSUE THREAD

**Issue by jerrulusfls** [AmazingApps/Amazing-Windows-Apps#169]
虽然腾讯在国内的名声一向不是很好，但腾讯桌面管家（[链接](http://pc.qq.com/detail/19/detail_23079.html)）还是相对良心的桌面整理软件。

特点：
1. 类似 Fences 的桌面分区
2. 支持文件夹映射
3. 自带本地搜索，速度还不错（开启比较隐蔽，在格子里右键选择打开本地搜索即可）
4. 似乎没有恶意\骚扰行为（就3个月使用而言）
5. 高分屏支持
6. 内存\CPU占用几乎可忽略不计（14.3MB 0%）

望采纳！

**Comment by EMLVIRUS** [comment]
@jerrulusfls ショック

**Comment by EMLVIRUS** [comment]
![image](https://user-images.githubusercontent.com/16912240/27513207-caf40dca-598f-11e7-8e98-7f5d34e086ea.png)

软件主程序向 TX 电脑管家发布 CDN 建立了连接，有点怕怕

**Comment by EMLVIRUS** [comment]
![image](https://user-images.githubusercontent.com/16912240/27513320-6c903cea-5994-11e7-8e60-65d7b974783f.png)

一个需要植入驱动，并且随时保持 IPC 通信的桌面管理工具，我对此持高度怀疑态度

**Comment by ivysrono** [comment]
建议对国内大厂建立黑名单，实行有罪推定。

**Comment by EMLVIRUS** [comment]
@ivysrono 这跟现在的黑名单有何区别

**Comment by ivysrono** [comment]
@EMLVIRUS 我还是喜欢原来的，对这些大厂仅列出没毛病的。

**Comment by ysc3839** [comment]
@EMLVIRUS 截图中有驱动吗？
