### ISSUE TITLE
能否添加一些比较著名的笔记类软件

### ISSUE THREAD

**Issue by lidacheng1** [AmazingApps/Amazing-Windows-Apps#172]
能否添加一些比较著名的笔记类软件
例如evernote等等

**Comment by EMLVIRUS** [comment]
evernote 我现在申请了免费账号一直在试用，但是限制很多，而且（在收费版如此贵的前提下）免费版还有广告，因此我一直很犹豫

Onenote并入在office套装中，没有单独列入

如果有别的好推荐，请每个推荐单独创建一个issue

**Comment by ysc3839** [comment]
Laverna

**Comment by EMLVIRUS** [comment]
> Laverna

See #182
