### ISSUE TITLE
CrystalDiskMark

### ISSUE THREAD

**Issue by EMLVIRUS** [AmazingApps/Amazing-Windows-Apps#181]
~（绝壁不是因为这死宅杀手的皮肤）~

**Comment by taroxd** [comment]
皮肤要 shizuku version 啊【

**Comment by EMLVIRUS** [comment]
~下载链接不都在一起咩~ 不过我居然一直漏了这个如此好用的测速工具

**Comment by taroxd** [comment]
~~在我下载 Windows 10 Store 版本的时候，我还需要切换到日区才能下载到 shizuku version~~

**Comment by Greedysky** [comment]
~~zdfans 你值得拥有~~
