### ISSUE TITLE
推荐一款很稳的能显著优化内存的工具

### ISSUE THREAD

**Issue by Sealt** [AmazingApps/Amazing-Windows-Apps#184]

**Comment by Sealt** [comment]
Mem reduct https://github.com/henrypp

**Comment by EMLVIRUS** [comment]
这一应用实质上将应用内存地址临时压缩至虚拟内存中，表面上剩余内存多了，但是实际上严重影响运行效率。如果真的内存不足，你需要的应该是新的哦内存条。
