### ISSUE TITLE
移除反病毒类应用

### ISSUE THREAD

**Issue by Rictusempra** [AmazingApps/Amazing-Windows-Apps#189]
且抛开测试难度的问题，如果用户知道仅从官网下载软件，那么这类软件毫无安装的必要。
对于那么不知道自己正在zuosi或者不怕死的，再多的安全措施也只是白费力气。

**Comment by ysc3839** [comment]
仅从官网下载也不能确保安全，有的软件官方就是捆绑了东西的。

**Comment by EMLVIRUS** [comment]
那样blacklist就好（或者参考eagleget（
