### ISSUE TITLE
一款开源 免费 好用的 GIF 录屏软件 Screen To Gif 

### ISSUE THREAD

**Issue by chrsas** [AmazingApps/Amazing-Windows-Apps#190]
一款开源 免费 好用的 GIF 录屏软件 Screen To Gif 
https://github.com/NickeManarin/ScreenToGif

**Comment by gloomy-ghost** [comment]
https://github.com/AmazingApps/Amazing-Windows-Apps/blob/12732aa5cf6c08c70c9d8fb056e46d7f1de853f2/en/practicals.md#L75

**Comment by EMLVIRUS** [comment]
@chrsas 这个GitHub项目主页还跟本项目有py关系

**Comment by chrsas** [comment]
@EMLVIRUS ,,ԾㅂԾ,,，我在图形图像里没看到，没想到在实用程序里。
