### ISSUE TITLE
个人开发效率应用 nTrun，Win+R模式快速启动+本地程序管理

### ISSUE THREAD

**Issue by Sealt** [AmazingApps/Amazing-Windows-Apps#194]
始于2014，详细介绍可以看官网 http://www.ntrun.com/
微博文章介绍 http://weibo.com/ttarticle/p/show?id=2309404140383025138683

无AD，全Win系统兼容

**Comment by EMLVIRUS** [comment]
@Sealt 既然您是作者，那么考虑到对应用的了解程度，我觉得由您自行提交 pull request 更为恰当

**Comment by Sealt** [comment]
怎么说呢……不是很了解GIT工作流的方式……

**Comment by EMLVIRUS** [comment]
那我来吧。不过您如果感兴趣，或者[这个项目](https://github.com/EMLVIRUS/GitHub-Beginners)会有所帮助

**Comment by Sealt** [comment]
非常感谢。

**Comment by EMLVIRUS** [comment]
@Sealt 繁体中文部分稍后跟进，期待更多合作
