### ISSUE TITLE
add Yu Writer

### ISSUE THREAD

**Issue by Rictusempra** [AmazingApps/Amazing-Windows-Apps#198]
https://ivarptr.github.io/yu-writer.site/

**Comment by gloomy-ghost** [comment]
Note on license:
![default](https://user-images.githubusercontent.com/13086421/30047550-f12464ea-9265-11e7-861c-8d18da5a319c.png)

**Comment by ivarptr** [comment]
This is an app base on [Electron](https://electron.atom.io/), so the files ffmpeg.dll and LICENSE are just come from electron prebuilt package, the Yu Writer is a close-source software.

**Comment by Rictusempra** [comment]
@ivarptr Thx for clarifying. You can expect Yu Writer listed in a few days.

**Comment by gloomy-ghost** [comment]
A license file in the root directory usually means it applies to the whole software, so you might want to change that...

See also: https://github.com/electron-userland/electron-builder/issues/916#issuecomment-260944707

**Comment by ivarptr** [comment]
@Rictusempra @gloomy-ghost Thank you very much!

**Comment by Rictusempra** [comment]
done in cf57669390b3bcd6599f55263aa81f39a931f36c
