### ISSUE TITLE
文件处理请求添加HashTab

### ISSUE THREAD

**Issue by xhml** [AmazingApps/Amazing-Windows-Apps#202]
该软件会嵌入文件属性窗口，作为一个Tab存在，更加方便易用。
软件地址：[HashTab](http://implbits.com/products/hashtab/)
软件截图：![Screenshot](http://www.sinaimg.cn/download/down_contents/1201363200/U74P176T43D37896F941DT20071227164006.jpg)

**Comment by ysc3839** [comment]
[HashCheck](https://github.com/gurnec/HashCheck) 看上去更好

**Comment by xhml** [comment]
功能和ui并没有更好，我懒得截图，找了一个xp年代的截图罢了，换成Windows10画风其实一样。。。
不过你提到的这个是开源的，这一点很好。

**Comment by ysc3839** [comment]
https://i0.wp.com/rubenalamina.mx/wp-content/uploads/2016/08/hashtab.png
找了一下，UI 和你给的截图没什么区别。功能的话确实 HashTab 支持更多 Hash 算法。

**Comment by xhml** [comment]
嗯，不过支持更多也没啥意义，常用的就是MD5、SHA-1、SHA-256和CRC32。总之选一个放进去吧，这种直接打开文件属性就能看到的交互方式和系统操作联系更紧密，交互习惯更加统一。
