### ISSUE TITLE
实用工具栏请求增加SpeQ Mathematics

### ISSUE THREAD

**Issue by tttsss520** [AmazingApps/Amazing-Windows-Apps#205]
SpeQ Mathematics是一款小巧强大的数学工具，仅仅600KB的大小提供了模型创建、工程计算、函数绘制等功能，支持多语言。作者同时提供了便携版本，可以装在U盘中在任意一台电脑上运行。免费无广告。最后更新时间是在2010年，但使用中没有发现重大BUG，完全满足一般人的使用需求。
官方网站 http://www.speqmath.com/?id=1

**Comment by Rictusempra** [comment]
1709 中已发现编码适配问题

![image](https://user-images.githubusercontent.com/16912240/31805694-66f455f2-b595-11e7-80ff-c6f47449beaa.png)
