### ISSUE TITLE
实用工具建议添加 MiniBin

### ISSUE THREAD

**Issue by SAN2333** [AmazingApps/Amazing-Windows-Apps#206]
一款在任务栏显示回收站图标的小工具，更新到现在6.6.0.0版本也仅有79kb的体积，可以设置图标样式，双击图标可以快速清空回收站，适用于因为美化而不想在桌面显示回收站图标或经常需要最大化程序窗口而不经常返回桌面的用户。

**Comment by Rictusempra** [comment]
您说的是这个吗：https://minibin.jaleco.com/

**Comment by SAN2333** [comment]
这个网站我这边打不开，我一直都是在https://e-sushi.net/ 这边找的，软件的关于界面也是指向这个页面的。

**Comment by SAN2333** [comment]
这个网站我这边打不开，我目前软件上指向的页面是http://www.e-sushi.net/minibin/ 但是我这边依旧无法打开。

**Comment by ysc3839** [comment]
http://e-sushi.github.io/

**Comment by SAN2333** [comment]
@ysc3839  感谢！看了一下确实是这个网站的东西，谢谢补充
