### ISSUE TITLE
效率工具/图形图像 请求添加 QuickLook

### ISSUE THREAD

**Issue by SAN2333** [AmazingApps/Amazing-Windows-Apps#209]
使用空格键快速预览的小软件，之前一直使用seer，跟seer比起来速度没有明显差异，但是无需自己添加复杂的插件来支持更多格式，没有复杂的设置项，官方也支持中文，所以从seer转向QuickLook，网站是http://pooi.moe/QuickLook/?utm_source=www.appinn.com

**Comment by Rictusempra** [comment]
已存在的应用

**Comment by SAN2333** [comment]
抱歉。。。
