### ISSUE TITLE
隐私安全：Simple Run Blocker 

### ISSUE THREAD

**Issue by HGladiator** [AmazingApps/Amazing-Windows-Apps#212]
[Simple Run Blocker](http://www.sordum.org/8486/simple-run-blocker-v1-4/) 
- 绿色简单小巧免费的软件禁用/屏蔽工具
- 禁止阻止运行指定软件游戏/隐藏禁用硬盘磁盘分区
- 支持黑白名单模式
- 支持中文

**Comment by HGladiator** [comment]
这网站上还有很多其他的作品，都是绿色小巧的工具，比如   

超简单限制禁止指定应用程序联网的防火墙工具 (绿色不占系统资源)的[Firewall App Blocker](http://www.sordum.org/8125/firewall-app-blocker-fab-v1-6/)

方便一键快速切换网卡DNS地址设置的免费实用工具 (批量测速/清空缓存等)的[DNS jumper](http://www.sordum.org/7952/dns-jumper-v2-1/)

还有二十多个小工具呢，都在[这里](http://www.sordum.org)，推荐去看看

**Comment by Rictusempra** [comment]
这些似乎都只是减少了一些操作而已。。。
至于 Simple Run Blocker ，我需要更多意见

**Comment by HGladiator** [comment]
功能的话也就是限制启动软件和隐藏磁盘分区，这些也只是减少一些操作而已。所以。。。
