### ISSUE TITLE
Eagleget存在写入未经签名的驱动文件的行为

### ISSUE THREAD

**Issue by weiyichen2011** [AmazingApps/Amazing-Windows-Apps#214]
Windows 7，64 bit。

![eagleget](https://user-images.githubusercontent.com/3448255/33304728-75ba39a2-d445-11e7-9cd0-0154d85ab62d.png)

**Comment by Rictusempra** [comment]
@weiyichen2011 准确来说是一个关于网络请求的模块
用于全局嗅探
虽然目前没有可疑行为
但是我还在观察
如果确实需要这一软件
你可以使用便携版

**Comment by weiyichen2011** [comment]
了解了，Thanks。
