### ISSUE TITLE
增加 网络通信: Puffin Browser

### ISSUE THREAD

**Issue by AaronSS** [AmazingApps/Amazing-Windows-Apps#219]
一款出色的基于云端渲染的浏览器,对带宽较低的人应该有所帮助,也可以拿来匿名.(可能被墙)
官网: https://www.puffinbrowser.com/index.html

**Comment by Rictusempra** [comment]
@AaronSS 我测试了半天，只有减速的效果。。。。。。。。

**Comment by AaronSS** [comment]
你在国内？你用这个浏览器跑一下speedtest就知道了

**Comment by Rictusempra** [comment]
怎么说呢，speedtest的结果还不如我自己搭建的瓦工SS。。。。
不过这也许会受到多方面影响，因此不太好说。
但是别的作为浏览器的体验。。。真的不敢恭维。。

**Comment by AaronSS** [comment]
我用speedtest跑出了900mbps的速度，可能测速点的带宽都不够了，另外你用的居然是搬瓦工哈哈哈

**Comment by Rictusempra** [comment]
@AaronSS 不不不
这是给舍友搭的。。。。
我自己有私用的拓扑网
抛开这个不说
就加速而言
个人觉得如果不适配大多数地区的情况
也没有意义的吧。。
毕竟ISP运营商还有QoS呢

**Comment by AaronSS** [comment]
第一次听说拓扑网可以用来科学上网，算是开眼界了，有相关资料吗，我要涨一下姿势。以前我也总是折腾怎么科学上网，无奈电信把国际宽带的线路的带宽都给企业用户了。最后直接肉身翻墙哈哈哈！

**Comment by Rictusempra** [comment]
@AaronSS 嗯。。。。。
你可能对拓扑有点误解。。。
我这个是用 38 台 Azure 服务器组件的树状拓扑
https://zh.wikipedia.org/wiki/%E7%BD%91%E7%BB%9C%E6%8B%93%E6%89%91
其中留出 3 台专门用于部署防御监控措施

**Comment by AaronSS** [comment]
明白了
