### ISSUE TITLE
生产工具#效率工具 请求添加【小黄条】

### ISSUE THREAD

**Issue by cg200776** [AmazingApps/Amazing-Windows-Apps#220]
无广告、无推送、从不主动打扰、免费
跨平台todolist，覆盖windows、andiord、IOS
跨平台同步，覆盖所有办公场景，随时随地查看、记录、编辑、管理任务
任务记录云端存储永不丢失
重要的事情可“置顶”，优先做
一览式todolist清单，简单、纯粹、实用
已完成的任务按天归档，方便快速回顾本周主要工作，高效输出工作周报
桌面便签支持嵌入桌面，搭配【极简】模式完美融入系统桌面
桌面便签窗体移动到屏幕边缘时自动隐藏，便于保护隐私
桌面便签支持自定义字体、字号、间距、文字颜色
桌面便签支持使用快捷键快速隐藏/显示主界面
App可对每个任务单独设置提醒
App图标可提示未完成任务数量
App支持Widget，Widget可快速完成任务，无需启动应用也能浏览、管理Todolist，更直观高效的自我管理
官网：
www.6fcsj.com
For Windows：
http://pc.qq.com/detail/11/detail_23251.html
For IOS：
https://itunes.apple.com/cn/app/id1175974945?mt=8
For andiord：
http://sj.qq.com/myapp/detail.htm?apkName=com.xiaohuangtiao

App满分好评率超95%：
http://fsight.qq.com/Game/1351731#/alldata

**Comment by Rictusempra** [comment]
@cg200776 这下载链接。。。怪怪的。。。
让人菊花发凉。。。

**Comment by cg200776** [comment]
上面那个是QQ软件管家里面的下载地址
这个是放在七牛云的客户端下载地址，版本号：V1.8.5
http://oi2cndzsh.bkt.clouddn.com/%E5%B0%8F%E9%BB%84%E6%9D%A1V1.8.5.exe

**Comment by cg200776** [comment]
补充：
便携软件或可便携安装
具有跨平台版本
多语言支持：windows、andiord、IOS 支持中文、英文

**Comment by Rictusempra** [comment]
未使用TLS传输数据

**Comment by cg200776** [comment]
@Rictusempra  下个版本搞定这个

**Comment by Rictusempra** [comment]
@cg200776 
如果你确认的话
可以reopen

**Comment by cg200776** [comment]
@Rictusempra  等我们搞定了 再来申请  现在上线时间暂时无法确定

**Comment by Rictusempra** [comment]
Reopen as feedback though I'm not sure whether we are to accept this.

**Comment by Rictusempra** [comment]
@cg200776 如果你们对你们的私有加密协议足够自信，那么当然是可以不部署 TLS 的
但是无论部署与否，都应该在 privacy terms 中予以说明（由于使用了公共云服务）
不过，贵司软件官网似乎无法找到相关条款

**Comment by cg200776** [comment]
For windows：
http://oi2cndzsh.bkt.clouddn.com/%E5%B0%8F%E9%BB%84%E6%9D%A1V1.9.0.exe
其它的版本今天刚提交，估计明后两天可以在各大应用市场下载到

**Comment by Rictusempra** [comment]
I need UX review here.
@ivysrono @gloomy-ghost , what do you think.

**Comment by ivysrono** [comment]
官网不支持HTTPS的新软件不敢用。

**Comment by Rictusempra** [comment]
> 官网不支持HTTPS的新软件不敢用

软件本身已支持 TLS 无疑，也许他们需要 Let's Encrypt ？
Anyway, 你可以尝试在虚拟机中运行它

**Comment by ivysrono** [comment]
等他们官网和下载全HTTPS了我再考虑。

**Comment by gloomy-ghost** [comment]
如果有 code signing 的话倒不用太纠结于下载的 TLS，其他东西之后有时间再看

> 10、修改与更新：由于本隐私政策可能不时被更新，您应定期查看以了解我们保护所收集之个人信息的方案及程序。您继续使用小黄条服务即构成您对本隐私政策及其任何更新版本的同意。

更新后没有通知用户的义务？

**Comment by gloomy-ghost** [comment]
基本功能没什么可以评价的，毕竟便签求的就是个简洁。对bug体质的人不友好(雾)，但加入国产良心没有太大问题。

https://img.vim-cn.com/a3/a84b99b43a54ad85e4a29b559a1bc74d36a914.webm

**Comment by gloomy-ghost** [comment]
For the record, r+ given:
- [ ] Signed with a valid code signature OR provide verified mechanism for distribution OR allow installing without admin privilege.

- Stipulate in writing that users will be noticed within [a time of period] when a event that would bring potential unwanted impact on users, including 
  - [ ] security breach
  - [ ] change of ownership
  - [ ] modification of privacy policy

**Comment by cg200776** [comment]
请问还需要我做什么不？

**Comment by Rictusempra** [comment]
@cg200776 暂时不需要
如果必要
我们会使用邮件通知您
这个应用已经被接受
稍等更新即可
后续建议已经在issue comment中写出

**Comment by cg200776** [comment]
非常感谢
