### ISSUE TITLE
输入法类应用程序求推荐

### ISSUE THREAD

**Issue by SawaraNazo** [AmazingApps/Amazing-Windows-Apps#221]
现在发现根本没有什么好用的输入法。
不是好用但广告太多（搜狗为代表），要不就不放心（百度、手心这类）。
微软自带的输入法还总是卡死。
请问你们有什么好的推荐吗？

**Comment by Rictusempra** [comment]
微软拼音我自己用着啥事没有。。
如果手心的360冠名介意的话
可以期待一下这个 https://github.com/copyliu/YIME

**Comment by SawaraNazo** [comment]
@Rictusempra 
谢谢回复。
微软拼音总的来说还行，但我这总是会出现莫名其妙的卡死，有时候明明是“中”，却打出来是英文，组词、联想也差一些，用起来确实不如搜狗畅快。
手心之前看不错，就试了下，结果中招了。会恶意篡改浏览器主页，才发现是360的 （。。
