### ISSUE TITLE
GUI for Aria2

### ISSUE THREAD

**Issue by Rictusempra** [AmazingApps/Amazing-Windows-Apps#224]
Yes, I have been asking for this since last year but still no suitable result that can be listed here.
It should fit the following standards:
- no per-configuration, which clearly decreases usability, required.
- wrap up all Aria2 function & logic
- update Aria2 release independently (optional)
- independent GUI executable
- support Windows 7/8.1/10. (if, meanwhile, mac OS and Linux, Qt or Electron will be better)

Clearly, I find none yet.

Yes, I know about [Persepolis Download Manager](http://persepolisdm.github.io/). Many features are missing there but I will keep an eye on it.

**Comment by Youxikong** [comment]
WebGUI [AriaNg](https://github.com/mayswind/AriaNg)
