### ISSUE TITLE
Typora 是国产软件。

### ISSUE THREAD

**Issue by szzhiyang** [AmazingApps/Amazing-Windows-Apps#235]
在 Typora 的 Credits 中可以发现作者自己也参与了 Typora 的简体中文汉化，并且他还在自己的推特上发送了不少简体中文推文。

**Comment by Rictusempra** [comment]
被明列为国产首先会咨询作者的意愿，如果作者不愿意被认出来，那我也没必要去说破

> 看破不说破，基友继续做

**Comment by szzhiyang** [comment]
@Rictusempra 

好的，懂你的意思。
