### ISSUE TITLE
免费驱动更新管理 DriverPack

### ISSUE THREAD

**Issue by AaronSS** [AmazingApps/Amazing-Windows-Apps#238]
官方网站: https://driverpack.io

**Comment by Rictusempra** [comment]
@AaronSS This accepted. Just need more investigation

**Comment by Rictusempra** [comment]
@AaronSS feel free to send PR as I'm a bit occupied now.

**Comment by Songxuewen** [comment]
注：可能会选择安装360 安全软件，建议仔细检查。

**Comment by AaronSS** [comment]
有点流氓，还是删除吧
