### ISSUE TITLE
自荐 Power Keys - 键盘流效率软件中的瑞士军刀

### ISSUE THREAD

**Issue by szzhiyang** [AmazingApps/Amazing-Windows-Apps#240]
[**Power Keys 官网**](https://github.com/szzhiyang/PerfectWindows/wiki/Power-Keys)

* 在 Power Keys 官网，您可以详细了解 Power Keys 的全部功能。

**Power Keys 优点** 

* 开源免费
* 简单易用
* 功能强大
* 开箱即用
* 能满足几乎所有与键盘相关的需求

希望更多需要它的人认识它，万分感谢！ 🙏

**Comment by Rictusempra** [comment]
This had been denied and marked as blacklist earlier.
Thx for posting though.

**Comment by szzhiyang** [comment]
@Rictusempra 

Could you please tell me the reason? I did nothing wrong.

**Comment by szzhiyang** [comment]
@Rictusempra 

Power Keys does not update automatically, autorun without permission, steal users' data or do any other wrong things. Why?

**Comment by Rictusempra** [comment]
What is blocked is Perfect Windows, which does nothing but changes system register keys and/or group policy values. Those changes suppose to have better Windows built-in features as successors without such a dirty way.
