### ISSUE TITLE
【申请收录】敬业签云便签

### ISSUE THREAD

**Issue by jingyeqian** [AmazingApps/Amazing-Windows-Apps#252]
敬业签 官网：https://www.jingyeqian.com/
敬业签下载地址：https://www.jingyeqian.com/windows/

敬业签是一款电脑和手机云同步的桌面便签软件，现敬业签支持Windows电脑版、Android安卓手机版、iPhone苹果手机版、iPad平板版、Web网页版，使用同一个敬业签账号登录可实现多端云同步便签内容。
联系方式：6817361@qq.com

**Comment by Riajyuu** [comment]
Thanks for applying.
We notice you have public server but privacy terms missed.
As our concern to privacy to our subscribers, this ticket is not closed as wont fix.
Feel free to reopen if you have fixed this.
