### ISSUE TITLE
About TIM｜关于TIM

### ISSUE THREAD

**Issue by Rictusempra** [AmazingApps/Amazing-Windows-Apps#57]
在稍早之前，[腾讯TIM已不再从黑名单中排除](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8d73ee4b793a3c83a7934a1e4976919becc93f92)

在TIM安装时，会在系统用户文件夹下留下腾讯电脑管家修复程序，该程序手动删除后，TIM会联网重新下载。
每当TIM个人文件夹大小达到用户指定的上限时，TIM会提醒用户清理，清理完毕后会提醒用户：”使用电脑管家全面深度清理电脑垃圾“
一旦用户点击该按钮，腾讯电脑管家修复程序便会联网下载安装腾讯电脑管家，**不会有任何额外确认提醒**；而应用**不仅严重侵犯用户隐私，还明显弱化系统安全性**。唯一阻止安装的办法是使用防火墙等联网控制工具阻止腾讯电脑管家修复程序联网。

鉴于此，不再将TIM从黑名单中排除，除非TIM添加补丁，移除该按钮与腾讯电脑管家修复程序

---

Some time earlier, [Tencent TIM is no longer excluded from black list](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8d73ee4b793a3c83a7934a1e4976919becc93f92).

When you install TIM, a fix program for Tencent PC manager will be added to system user folder. TIM will re-download it if you delete it manually.
Whenever your TIM user folder size reach the limit you set, TIM will notify you to clean it. But you will told "Use Tencent PC manager to further clean PC"
Once you click it, **without another confirmation**, the fix program will download and install Tencent PC manger, which **severely invades user privacy and also weaken system stability**. The only solution is to limit the fix program from Internet.

Therefore, TIM is no longer excluded from blacklist unless Tencent remove the button and the fix program.

**Comment by kongxi0071** [comment]
这个程序组件在WIN10系统因数字签名问题会被系统禁用。

**Comment by EMLVIRUS** [comment]
> 这个程序组件

您是指哪个组件?

**Comment by EMLVIRUS** [comment]
关于TIM的其它疑问请新建issue，此处仅作备忘
