### ISSUE TITLE
Eeagleget无法在Windows 10 RS 2插入网络驱动

### ISSUE THREAD

**Issue by kongxi0071** [AmazingApps/Amazing-Windows-Apps#67]
win10系统下数字签名问题

截图：https://drive.google.com/open?id=0B-igoTpY7I2fNG5fY2VVUG42MW8

**Comment by EMLVIRUS** [comment]
链接无效，此外GitHub可以附带图片，复制到剪贴板之后粘贴到输入框即可

**Comment by EMLVIRUS** [comment]
这是由于第三方软件拦截导致的，目前eaglget使用的证书
![image](https://cloud.githubusercontent.com/assets/16912240/25328724/8dd40d78-290b-11e7-8b5a-2959087bee2a.png)
暂时仍旧属于可信状态

**Comment by taroxd** [comment]
那个数字签名不是指软件的数字签名，是指驱动程序有没有经过微软的签名吧。

和第三方软件没有什么关系的 @EMLVIRUS

**Comment by EMLVIRUS** [comment]
我想歪了？

因为驱动签名问题我在虚拟机测试的时候没有发现

**Comment by taroxd** [comment]
我没测试过这个软件，只是同样的问题我在 QQ 上见过（现在 QQ 应该已经适配创意者更新，不会有这问题了）

**Comment by EMLVIRUS** [comment]
> 这个需要那边软件的开发者适配创意者更新

言下之意：此问题非本列表涉及问题？
至少我是这么想的

**Comment by EMLVIRUS** [comment]
@kongxi0071 如有疑问，请重新open，这超出本列表范畴

**Comment by EMLVIRUS** [comment]
@kongxi0071 我昨天尝试了一次 并未发现网络驱动无法注入的问题
这就很奇怪
